packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@carbon/icon-helpers': set this to true or false
  '@carbon/icons-react': set this to true or false
  esbuild: true
  unrs-resolver: true

onlyBuiltDependencies:
  - unrs-resolver
